export const ALL_CAMPAIGNS = 'all_campaigns'
export const COMPANIES = "companies"

export const JOBSEEKER_APPLICATION_SUBMITTING_STARTED = 'JOBSEEKER_APPLICATION_SUBMITTING_STARTED'
export const JOBSEEKER_APPLICATION_SUBMITTING_SUCCESSFUL = 'JOBSEEKER_APPLICATION_SUBMITTING_SUCCESSFUL'
export const JOBSEEKER_APPLICATION_SUBMITTING_FAILED = 'JOBSEEKER_APPLICATION_SUBMITTING_FAILED'

export const SAVE_TO_VIEW_ADDITIONAL_QUESTIONS = "SAVE_TO_VIEW_ADDITIONAL_QUESTIONS"