export const ALL_CAMPAIGNS = 'all_campaigns'
export const COMPANIES = "companies"

export const CREATE_CAMPAIGN_SUBMITTING_STARTED = 'CREATE_CAMPAIGN_SUBMITTING_STARTED'
export const CREATE_CAMPAIGN_SUBMITTING_SUCCESSFUL = 'CREATE_CAMPAIGN_SUBMITTING_SUCCESSFUL'
export const CREATE_CAMPAIGN_SUBMITTING_FAILED = 'CREATE_CAMPAIGN_SUBMITTING_FAILED'